### ISSUE TITLE
Move more towards MVVM architecture

### ISSUE THREAD

**Issue by NeilMacMullen** [NeilMacMullen/Textrude#15]
The current TextrudeInteractive code was thrown together quickly as a demonstrator.  Would be nice to architect it a little mode cleanly and support some unit testing.

**Comment by Jlll1** [comment]
I'd love to try this task.

**Comment by NeilMacMullen** [comment]
That would be great - go for it !  :-) As a practical matter, I would suggest doing this  in a series of small steps and merging often.  I'm still actively working on MainWindow code-behind and I know @highstreeto  is working on InputPane and OutputPane  (see #7 )so there's quite a large potential for conflicts over the next week or so.

**Comment by NeilMacMullen** [comment]
... and if you have questions feel free to drop me a line here.  Hopefully the main code is fairly self-explanatory. The "heart" of MainWindow is every user input is wired up to OnModelChanged which collects the input state and drops it into an Observable.   The observable  renders the results via the Render method.  The rendered output is then dropped back into the UI via the HandleResults method

**Comment by NeilMacMullen** [comment]
I have just committed a significant reordering of MainWindow.xaml.cs This moves all related methods in to regions.  Hopefully this should make it more obvious what does what and help avoid conflicts.  My changes from here on  should be a lot more localised and easier to merge.

**Comment by Jlll1** [comment]
Is there something wrong with me creating a new project for that for the ease of operating, since it's a rebuild anyway, or should I stick to modifying the existing one?

**Comment by NeilMacMullen** [comment]
> Is there something wrong with me creating a new project for that for the ease of operating, since it's a rebuild anyway, or should I stick to modifying the existing one?

I don't think it should be a new project - *most* of the code will be the same.  It's really mostly a matter of moving code in MainWindow.xaml.cs into a viewmodel then binding up the UI.  (Actually the binding could be done first using the MainWindow as its own datacontext and creating a standalone VM done as a final step)

The good news is that most of the "big" changes are now done - the main one to watch out for is that we might rework the TabControlManager so that it doesn't really use tabs (see #45 )

**Comment by Jlll1** [comment]
Is it okay if I made a WIP PR?

**Comment by NeilMacMullen** [comment]
> Is it okay if I made a WIP PR?

Yes of course!  If you already know this stuff please ignore the rest of this message, but if you don't...  

The "process" is:
- you make changes on your fork then raise a PR for me to accept and merge.
- Ideally the PR is the smallest change that makes a meaningful difference. (Being small makes it easier to review!)
- I won't "accept" a PR if it breaks any of the unit tests or the application(s).  (We're currently treating 'main' as always releasable and don't (yet) use a dev brancch.)
- If you just want to get comments or advice on your PR then there is an option when you raise it to mark it as "draft" or "in progress" I think.  That stops me being able to merge it.
- If you have particular questions about the changes you have made, you can put some text in the PR submission explaining what you are unsure about.

Look forward to seeing it :-)

**Comment by Jlll1** [comment]
Hey. I'm sorry but due to some unexpected circumstances I won't be able to find any time to work on this.
If no one picks it up until next week, I'll gladly come back to it.

Sorry for wasting your time.

**Comment by NeilMacMullen** [comment]
No worries - come back any time :-)

**Comment by NeilMacMullen** [comment]
closing - it's good enough for now
