### ISSUE TITLE
Install textrude cli using dotnet tool install

### ISSUE THREAD

**Issue by AdamCoulterOz** [NeilMacMullen/Textrude#232]
Publish the textrude cli as a dotnet tool package on NuGet, this way it can be installed by anyone (Windows or Linux) using:

```sh
dotnet tool install --global textrude
```

Instructions on how to do it are here: https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create

it seems it mostly just involves adding these 2 tags to the `Textrude.csproj` file:

```xml
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>textrude</ToolCommandName>
```

This approach seems more appropriate rather than a library, as if you wanted to use the library you would install `scriban` directly.

You could do the same for the interactive tool, but I would list that as a different NuGet tool package i.e. `textrude-interactive`

**Comment by NeilMacMullen** [comment]
Got this working for the CLI ... (test build available via `dotnet tool install --global textrudecli`) but I don't think it's currently possible for the interactive version.  Having said that, I don't think that's so important - might take a look at distributing that via msix.

**Comment by NeilMacMullen** [comment]
hmm - having said that, extra work would be required to get the libs folder packed this way
