### ISSUE TITLE
How to get CSV headers dynamically?

### ISSUE THREAD

**Issue by wakuflair** [NeilMacMullen/Textrude#233]
I want to render the CSV headers in the output,
I tried `model.Headers[0]`, `row.Columns[0]`, `row.Keys[0]`, but none of them works.

I checked the source, seems there is no way to get CSV headers.
Am I missing anything?

**Comment by NeilMacMullen** [comment]
Can you explain the scenario?  Textrude turns rows in the CSV into objects whose properties are named after the csv column headers so It's hard for me to imagine how you could write any kind of script without knowing the column names but I'm probably missing something.  If you just want to write a csv back out again you can use the textrude.to_csv method.  

All objects are treated internally as ScriptObjects  IIRC there is a way to enumerate the properties (i.e. header names) but I'll need to check on that.

**Comment by NeilMacMullen** [comment]
LIke this... 
![image](https://user-images.githubusercontent.com/9131337/153368223-9fbfc733-827f-4883-9725-e583e0996cd8.png)

**Comment by NeilMacMullen** [comment]
And here's an example of using to_csv...

![image](https://user-images.githubusercontent.com/9131337/153384538-3cf9a828-a9e1-483e-a11e-ba746d2152e8.png)

**Comment by wakuflair** [comment]
Hi @NeilMacMullen 
My scenario is using textrude to generate a markdown table from a CSV text:

CSV:
``` csv
Name, Age
Alice, 22
Bob, 35
```

to generate:
```
| Name | Age |
|------|-----|
| Alice| 22  |
| Bob  | 35  |
```

So I need to get the CSV headers(`Name` and `Age` here) and use them in the output.

Seems `object.keys model[0]` is the solution, I'll try it, thanks!

**Comment by wakuflair** [comment]
Oh that helps a lot, thanks!
