### ISSUE TITLE
Create an attractive icon/logo

### ISSUE THREAD

**Issue by NeilMacMullen** [NeilMacMullen/Textrude#30]
I have no graphic design skills :-(  Maybe someone can up with something appealing to the eye.

**Comment by highstreeto** [comment]
I made some mock-ups in Inkscape of a larger logo and an app icon. The idea of them was that the output is "extruded" from the template as hinted by the 3D effect (in some variants) and curly braces.

I am no graphics designer myself, so no idea if the used colors work or the effects do their thing.

Here a PNG preview (PDF is at bottom)

![textrude_logo](https://user-images.githubusercontent.com/999260/107879816-6c5f2500-6edb-11eb-96f5-bb30f2d92c2c.png)

[textrude_logo.pdf](https://github.com/NeilMacMullen/Textrude/files/5977907/textrude_logo.pdf)

**Comment by NeilMacMullen** [comment]
Wow- those are really nice! Thoughts...

The braces are a brilliant touch. Not only do they represent Scriban but they give a "shaking" effect which to my eyes represents the active/interactive nature of the tool and also can be seen as extruded layers. 

Big logo...

Of 1/2 I think I actually prefer 1 - the extrusion on the text is nice but the flat text has a classic simplicity.  In some ways it looks like a stencil which is also quite appropriate.

App icon...

Again, I think simpler is actually more effective.  1 & 4 are my favourites but 1 is probably more effective as a small icon?

**Comment by NeilMacMullen** [comment]
Hmm - having said that I  do keep coming back to the large 2 with the extrusion! Has to be pretty big though - when zoomed out it just looks blurry.

**Comment by highstreeto** [comment]
I made the big logos a bit bigger. Hm. both (now) 1 and 3 look good

For the app icon: I think the 1 fits best, because of its simplicity

![textrude_logo_v2](https://user-images.githubusercontent.com/999260/107880891-e7c3d500-6ee1-11eb-83d1-65b64790a159.png)

**Comment by NeilMacMullen** [comment]
Big logo,,,
- I think the weight of the braces on 3 is slightly better .  
- Sharp corners on 2 work well - gives it a good "stencil" look

I would almost have to flip a coin to choose between 2&3 but I'm leaning towards 3 !

App icon
 What do you think about square with sharp edges ? Something like.,..

![image](https://user-images.githubusercontent.com/9131337/107881675-4d619280-6edd-11eb-8fdc-077f14af2b1a.png)

**Comment by highstreeto** [comment]
Hm, yeah sharp edges work too. Was the blue border intentional? Because I would keep it monochrome.
I changed the sharp corners, and now we have this:

![textrude_logo_v3](https://user-images.githubusercontent.com/999260/107883464-62472180-6eef-11eb-9740-03a3a733b164.png)

**Comment by NeilMacMullen** [comment]
Sold! 

>Was the blue border intentional? 

No - just an artefact of using PowerPoint for a quick mockup - definitely agree the monochrome is better. :-)

**Comment by highstreeto** [comment]
Ok, cool :)

I will open a PR in the near future, but it could take some time to adapt the App Icon to the correct format and possibly add some white background for better visibility.

**Comment by NeilMacMullen** [comment]
Nice - thanks very much!  I'll probably make a release (1.4) later tonight if I get some other stuff finished but no hurry  :-)

**Comment by NeilMacMullen** [comment]
Closing.  Thanks - definitely makes 1.4 look  a lot more professional!
