### ISSUE TITLE
Investigate visual artefacts on Monaco editor

### ISSUE THREAD

**Issue by NeilMacMullen** [NeilMacMullen/Textrude#41]
Monaco editor seems to flash white when tab switching or resizing its container.  Possibly this is "just the way things are" with Monaco/Webview running inside WPF at this stage but would be nice to resolve.

**Comment by NeilMacMullen** [comment]
Startup is very slow as well if there are multiple model/output tabs.  I thought this was due to the time it took to extract files from the embedded resource but actually it's not. Most likely it's just process startup time.

**Comment by highstreeto** [comment]
> We do seem to have more processes than required though. For a 3 model, 3 output project I seem to spawn 11 processes!
It seems this is just how WebView2 (and Chromium) works: they are processes spawned for each tab, utility, render and (I think) the web workers use some processes too (but seem to be shared).

For a breakdown, the Browser Task Manager can be used (right-click the DevTools Header bar):
![textrude_tasks](https://user-images.githubusercontent.com/999260/106399256-dbd31000-6417-11eb-96f0-674a6ce057a7.png)

To open the dev tools, add (for example, as a reminder):
```csharp
_monacoBinding.Initialize()
  .ContinueWith(_ => { _monacoBinding.OpenDevTools(); }, TaskScheduler.FromCurrentSynchronizationContext())
  .ConfigureAwait(false);
```

**Comment by NeilMacMullen** [comment]
>To open the dev tools, add (for example, as a reminder):

Nice, thanks!  I *really* like the visual styling from Monaco and I think  #45 and #47 would go quite a long way to reducing the perceived impact.  As it is now, the perf is pretty good for a single-model, single output project.  The " "context search" when selecting an output format is very nice - I was going to suggest that a feature so nice that it comes for free!

**Comment by NeilMacMullen** [comment]
Closing - i think we're getting pretty close and #45 will pretty much complete this.
