### ISSUE TITLE
Reduce visual impact of slow Monaco loading by providing spinner background

### ISSUE THREAD

**Issue by NeilMacMullen** [NeilMacMullen/Textrude#47]
The monaco tabs can take a long time to load (e.g. when adding a new model or output).  This could be made a bit less visually intrusive by providing a panel overlay with dark background and spinner and making it visible until the webview receives the "ready" message.

**Comment by highstreeto** [comment]
One problem can be, that the WebView2 is derived from [HwndHost](https://docs.microsoft.com/en-us/dotnet/api/system.windows.interop.hwndhost?view=net-5.0), which brings some problems (see [WPF and Win32 Interoperation](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/wpf-and-win32-interoperation?view=netframeworkdesktop-4.8#notable-differences-in-output-behavior)) and the biggest of which is, that the Win32 window is always rendered on top.

**Comment by NeilMacMullen** [comment]
Hmm - maybe we start with the WebView control at minimal size then expand it when ready?

**Comment by highstreeto** [comment]
> Hmm - maybe we start with the WebView control at minimal size then expand it when ready?

Hah, never thought of that :) seems to work better (a shorter flash)
![textrude_monaco_min_to_max](https://user-images.githubusercontent.com/999260/106400354-3bccb500-641e-11eb-9837-124d90ea1e8e.gif)

**Comment by NeilMacMullen** [comment]
excellent :-)

**Comment by NeilMacMullen** [comment]
Closing.  I also forced a language load and editor layout before issuing Ready which seems to help a bit.
