### ISSUE TITLE
Feature - File input for models in TextrudeInteractive

### ISSUE THREAD

**Issue by highstreeto** [NeilMacMullen/Textrude#8]
Copying the file contents into the models tab is a bit clunky, would be cooler, if a file could be chosen directly.

This could look, for example, look like this:
![model_file_input](https://user-images.githubusercontent.com/999260/105718366-71a30280-5f21-11eb-8efa-f013d0975895.png)

**Comment by NeilMacMullen** [comment]
Yes agreed! (see my slightly longer answer at https://github.com/NeilMacMullen/Textrude/discussions/7#discussioncomment-308693) but this actually the way one of the very early prototypes worked.  I found the UI got a little confusing since the input windows could now be...

- text with no backing file
- text loaded from a backing file but edited in the input window (no link back to the originating file except maybe for explicit save?)
- text loaded from a 'live' linked file (text changes if user edits the original file).  What happens if the user edits the file in both places? Probably easiest to just disable editing in the edit window in this case.

**Comment by highstreeto** [comment]
Hm, good point. Maybe models could have two "modes":

1. Backed by a file and read-only
2. Free input

This would probably need some descriptive icons to distinguish the two easily.

Or the models are always backed by files and can be edited in TextrudeInter. and when external changes are detected, a reload or discard can be done (like Notepad++):
![notepadpp_reload](https://user-images.githubusercontent.com/999260/105725362-27258400-5f29-11eb-8aa0-5d5dcf42cdf3.gif)

But I think the "2-mode" idea would be a bit more consistent for the user...

**Comment by NeilMacMullen** [comment]
Out of interest, is your main use-case 

- you have some existing files and just want to get them into the UI so you can start playing with a template?
- you anticpate your model/template files to be under active development outside the tool and periodically want to reload them
- you want to use an external editor to edit the models/template "live"

I'm sure you have already worked out that the "Project/save/load/export as invocation provides a (clunky) persistence mechanism while developing new templates?

Blocked by https://github.com/NeilMacMullen/Textrude/issues/10#issue-793532970

**Comment by highstreeto** [comment]
My current use case is:
1. develop a template that uses a CSV file to generate some C# classes, which should be incorporated into a VS project
2. save the finished template in the solution and generate C# files in the Pre-Build step

The models will probably be static at 2., only at 1 they are dynamic, as I have to evaluate which pieces of info. needed to be passed on to the C# classes, so it works with the existing system.
I am also considering replacing some T4 templates, which generate C# files from YAML files, but this comes maybe later

**Comment by NeilMacMullen** [comment]
Thanks.  I think the best workaround for now would to set up a project to hold the models and template during #1 then use the "export as invocation" step when you're ready to move onto #2.  I think the changes discussed here are a good idea but may take a while (I'm currently trying to flesh out some C# code templates in 'libs')

**Comment by highstreeto** [comment]
Yeah, that works for me.

No sweat, the things I want to do, work, so no hurry :)

**Comment by NeilMacMullen** [comment]
Partially done - head of main includes a "Load" button on each model tab.  Similarly there is a "save" button on each output tab.  Not quite as good a live link but may be useful.

**Comment by highstreeto** [comment]
Cool :) (and helps for existing data)

Thinking about, this would be (probably) enough, as this could get out of hand fast (as discussed).
If they are no other objections, I would close this issue.

**Comment by NeilMacMullen** [comment]
> If they are no other objections, I would close this issue.

Super - btw, just started looking at your monaco branch.  Are you still playing with it or are you happy for me to rip the code and integrate it?

**Comment by highstreeto** [comment]
For `monaco`: see [#7](https://github.com/NeilMacMullen/Textrude/discussions/7#discussioncomment-321048), there could be some problems integrating it right now
